const actionsType = {
  ACT_LOGIN: 'user/ACT_LOGIN',
  ACT_GET_ALL: 'user/ACT_GET_ALL',
  ACT_SIGNOUT: 'user/ACT_SIGNOUT',
  ACT_SIGNUP: 'user/ACT_SIGNUP',
  ACT_FETCH_GET_USER_NOT_MEMBER: 'user/ACT_FETCH_GET_USER_NOT_MEMBER',
  ACT_CHANGE_ROLE: 'user/ACT_CHANGE_ROLE',
  ACT_SEARCH: 'user/ACT_SEARCH',
  ACT_FETCH_WITH_SYSTEM_ROLE: 'user/ACT_FETCH_WITH_SYSTEM_ROLE',
};

export default actionsType;
