const mutationsType = {
  MUTATE_LOGIN: 'user/MUTATE_LOGIN',
  MUTATE_SET_LIST_USERS: 'user/MUTATE_SET_LIST_USERS',
  MUTATE_SIGNOUT: 'user/MUTATE_SIGNOUT',
  MUTATE_SET_USER_NOT_MEMBER: 'user/MUTATE_SET_USER_NOT_MEMBER',
  MUTATE_SET_PROFILE: 'user/MUTATE_SET_PROFILE',
  MUTATE_SET_IS_LOGIN: 'user/MUTATE_SET_IS_LOGIN',
  MUTATE_SET_WITH_SYSTEM_ROLE: 'user/MUTATE_SET_WITH_SYSTEM_ROLE',
  MUTATE_SET_IS_ONLINE: 'user/MUTATE_SET_IS_ONLINE',
};

export default mutationsType;
