const actionTypes = {
  GET_GAME: 'game/GET_GAME',
  INVITE_PLAYERS: 'game/INVITE_PLAYERS',
  KICK_PLAYER: 'game/KICK_PLAYER',
  START_GAME: 'game/START_GAME',
  RESET_GAME: 'game/RESET_GAME',
  FINISH_GAME: 'game/FINISH_GAME',
  DELETE_GAME: 'game/DELETE_GAME',
  ACCESS_GAME_GUEST: 'game/ACCESS_GAME_GUEST',
  ACCESS_GAME: 'game/ACCESS_GAME',
  GAME_SNACKBAR: 'game/GAME_SNACKBAR',
  SUBMIT_GAME: 'game/SUBMIT_GAME',
  ENABLE_CARD: 'game/ENABLE_CARD',
  DISABLE_CARD: 'game/DISABLE_CARD',
  ACT_CREATE: 'game/ACT_CREATE',
  SET_HISTORY: 'game/SET_HISTORY',
  GET_PLAYERS: 'game/GET_PLAYERS'
};

export default actionTypes;
