const getterTypes = {
  GET_GAME_MANAGEMENT: 'game/GET_GAME',
  GET_USERS: 'game/GET_USERS',
  GET_PLAYERS: 'game/GET_PLAYERS',
  GET_MEMBERS: 'game/GET_MEMBERS',
  GET_ALERT: 'game/GET_ALERT',
  GET_SUMMARY_STORY_POINTS: 'game/GET_SUMMARY_STORY_POINTS',
  GET_SUMMARY_PLAYERS: 'game/GET_SUMMARY_PLAYERS',
  GET_IS_START_GAME: 'game/GET_IS_START_GAME',
  GET_ACCESS_GAME_GUEST: 'game/GET_ACCESS_GAME_GUEST',
  GET_ACCESS_GAME: 'game/GET_ACCESS_GAME',
  GET_GAME_SNACKBAR: 'game/GET_GAME_SNACKBAR',
  GET_STATUS_CARD: 'game/GET_STATUS_CARD',
  GET_CREATE_RESULT: 'game/GET_CREATE_RESULT',
  GET_HISTORY: 'GET_HISTORY',
  GET_FINISH_GAME: 'game/GET_FINISH_GAME',
  GET_TOTAL_PLAYERS: 'game/GET_TOTAL_PLAYERS'
};

export default getterTypes;
