const mutationTypes = {
  SET_GAME: 'game/SET_GAME',
  SET_PLAYERS: 'game/SET_PLAYERS',
  SET_USERS: 'game/SET_USERS',
  SET_SELECTED_EMAILS: 'game/SET_SELECTED_EMAILS',
  SET_ENTERED_EMAILS: 'game/SET_ENTERED_EMAILS',
  SET_SUMMARY_STORY_POINTS: 'game/SET_SUMMARY_STORY_POINTS',
  SET_SUMMARY_PLAYERS: 'game/SET_SUMMARY_PLAYERS',
  SET_MEMBERS: 'game/SET_MEMBERS',
  SET_IS_START_GAME: 'game/SET_IS_START_GAME',
  SET_IS_RESET_GAME: 'game/SET_IS_RESET_GAME',
  SET_IS_FINISH_GAME: 'game/SET_IS_FINISH_GAME',
  SET_ALERT: 'game/SET_ALERT',
  ACCESS_GAME_GUEST: 'game/ACCESS_GAME_GUEST',
  ACCESS_GAME: 'game/ACCESS_GAME',
  GAME_SNACKBAR: 'game/GAME_SNACKBAR',
  ENABLE_CARD: 'game/ENABLE_CARD',
  DISABLE_CARD: 'game/DISABLE_CARD',
  SET_CREATE_RESULT: 'game/SET_CREATE_RESULT',
  SET_HISTORY: 'game/SET_HISTORY',
  SET_TOTAL_PLAYERS: 'game/SET_TOTAL_PLAYERS'
};

export default mutationTypes;
