const actionTypes = {
  GET_NOTIFICATION_LIST: 'notification/GET_NOTIFICATION_LIST',
  GET_NOTIFICATION_LIST_POPUP: 'notification/GET_NOTIFICATION_LIST_POPUP',
  CHANGE_NOTIFICATION_STATUS: 'notification/CHANGE_NOTIFICATION_STATUS',
  GET_NOTIFICATION_QUANTITY: 'notification/GET_NOTIFICATION_QUANTITY',
  GET_UNREAD_COUNT: 'notification/GET_UNREAD_COUNT',
  ACCEPT_INVITE_GAME_NOTIFICATION:
    'notification/ACCEPT_INVITE_GAME_NOTIFICATION',
  CHANGE_TO_READ_STATUS: 'notification/CHANGE_TO_READ_STATUS',
  ACT_SEARCH: 'notification/ACT_SEARCH',
};

export default actionTypes;
