const MESSAGE = {
  CREATE_FAIL: 'Cannot create. Please check your content before creating',
  CREATE_SUCCESS: 'Created successfully',
  FIND_SUCCESS: 'Find successfully',
  FIND_EMPTY: 'No search results',
  UPDATE_SUCCESS: 'Updated successfully',
  UPDATE_FAIL: 'Cannot update. Please check your content before updating',
  DELETE_SUCCESS: 'Deleted successfully',
  DELETE_ALREADY: 'Cannot delete. This row was deleted by another person',
  DELETE_FAIL: 'Cannot delete. Please check your content before deleting',
  NOT_EMPTY_PROJECT_NAME: 'Please enter project name',
  NOT_EMPTY_USER_NAME: 'Please enter user name',
  NOT_EMPTY_PASSWORD: 'Please enter password',
  NOT_EMPTY_EMAIL: 'Please enter email address',
  NOT_EMPTY_PRODUCT_BACKLOG_NAME: 'Please enter product backlog name',
  INVALID_USERNAME: "The username that you've entered is incorrect",
  INVALID_PASSWORD: "The password that you've entered is incorrect",
  USER_NOT_PERMISSION: 'You do not have permission to access',
  USER_NEED_LOGIN: 'You need to login',
  PASSWORD_NOT_MATCH: 'Password and confirm password are not matched',
  USER_ALREADY_ACTIVE: 'Your account already actived',
  USER_ACTIVE_SUCCESS: 'Your account active success',
  SERVER_ERROR: 'Server error. Please try again later',
  DATE_END_ERROR: 'Invalid end date',
  LOGIN_SUCCESS: 'Your login was successful',
  INVITE_PLAYERS_SUCCESS: 'Invite players successfully',
  INVITE_PLAYERS_FAIL: 'You invite players who already invited',
  KICK_PLAYER_SUCCESS: 'Kick player successfully',
  START_GAME_SUCCESS: 'Started game successfully',
  GAME_ALREADY_STARTED: 'Game has already started',
  RESET_GAME_SUCCESS: 'Reset game successfully',
  FINISH_GAME_SUCCESS: 'Finished game successfully',
  DELETE_GAME_SUCCESS: 'Deleted game successfully',
  GAME_NOT_FOUND: 'Game not found',
  PLAYER_NOT_FOUND: 'Player not found',
  GAME_NOT_START: 'Game has not started yet',
  NO_ONE_TO_INVITE: 'No one to invite',
  TOKEN_EXPIRED: 'Token expired. Login again',
  TOKEN_INVALID: 'Token invalid. Please try again later',
  GAME_ALREADY_START: 'Game already started',
  SELECT_CARD_MUST_A_NUMBER: 'Card must be a number from 0 to 999',
  YOU_ARE_KICKED: 'Sorry! You were kicked from this game.',
  NOT_DELETE_GAME_PLAYING: "Can't delete! Your game is playing!",
  NOT_AUTHOR_PERFORM: 'You are not authorized to perform this feature',
  NOT_AUTHOR_ACCESS: 'You are not authorized to access',
  NOT_EMPTY_CARD: 'Please pick your card',
  NOT_EMPTY_COMMENT: 'Please write your comment',
  IMAGE_TOO_LARGE:
    'Sorry, the image you are trying to upload is too big (maximum size is less than 3MB).',
  IMAGE_TYPE_ERROR:
    'Sorry, the file you are trying to upload is not a valid image type. Please try again',
  NOT_MEMBER_IN_PROJECT:
    "You are not authorized to access. You are't member of this project.",
  NOT_PM_IN_PROJECT:
    "You are not authorized to access. You aren't project manager of this project.",
  NOT_ADMIN: "You are not authorized to access. You aren't admin.",
  PM_DELETE_PROJECT: 'Your project has delete',
  MENBER_ALREADY_EXITSTS: 'Member already exists',
  BACKLOG_WAS_REMOVE: 'This backlog was removed',
  BACKLOG_NOT_EXISTED: "This backlog doesn't exist!",
  PROJECT_NOT_EXISTED: "This project isn't existed!",
  GAME_NOT_EXISTED: "This game doesn't exist",
  MENBER_DOES_NOT_EXITSTS: 'Member doesn\'t exist',
  ACCOUNT_HAS_BEEN_DELETED:
    'Your account has been deleted',
  GAME_AUTO_FINISHED:
    'All players have left the game so the game will end automatically',
  GAME_JOINED_USER: 'You are already join game in somewhere!',
  GAME_ALREADY_FINISH: 'Game are already finished',
  GAME_ALREADY_JOINED: 'You are already join game in somewhere!',
};

export default MESSAGE;
