const actionTypes = {
  ACT_GET_DETAIL_BY_ID: 'project/ACT_GET_DETAIL_BY_ID',
  ACT_CREATE: 'project/ACT_CREATE',
  ACT_GET_PROJECT_BY_ID: 'project/ACT_GET_PROJECT_BY_ID',
  ACT_UPDATE_PROJECT_BY_ID: 'project/ACT_UPDATE_PROJECT_BY_ID',
  ACT_FETCH_GET_ALL_PROJECTS: 'project/FETCH_GET_ALL_PROJECTS',
  ACT_FETCH_DELETE_PROJECT: 'project/FETCH_DELETE_PROJECT',
  ACT_FETCH_GET_ALL_MEMBERS: 'project/FETCH_GET_ALL_MEMBERS',
  ACT_SEARCH_PROJECTS: 'project/ACT_SEARCH',
  ACT_CHECK_PLAYING: 'project/ACT_CHECK_PLAYING',
  ACT_FETCH_EDIT_BY_ID: 'project/FETCH_EDIT_BY_ID',
};

export default actionTypes;
