const getterTypes = {
  GET_SNACKBAR: 'GET_SNACKBAR',
  GET_CREATE_RESULT: 'GET_CREATE_RESULT',
  GET_DELETE_RESULT: 'GET_DELETE_RESULT',
  GET_INVITATION_POPUP: 'GET_INVITATION_POPUP',
};

export default getterTypes;
