const mutationTypes = {
  SET_SNACKBAR: 'SET_SNACKBAR',
  SET_CREATE_RESULT: 'SET_CREATE_RESULT',
  SET_DELETE_RESULT: 'SET_DELETE_RESULT',
  SET_INVITATION_POPUP: 'SET_INVITATION_POPUP'
};

export default mutationTypes;
